In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df=df.drop(columns=['RowNumber','CustomerId','Surname'])

In [5]:
df.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [6]:
df.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
import sklearn

In [9]:
#help(sklearn.preprocessing)

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
#help(StandardScaler)

In [12]:
df['Geography'][df['Geography']=='France']=0
df['Geography'][df['Geography']=='Spain']=1
df['Geography'][df['Geography']=='Germany']=2 
df['Gender'][df['Gender']=='Male']=0
df['Gender'][df['Gender']=='Female']=1

/tmp/ipykernel_8907/3606293857.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Geography'][df['Geography']=='France']=0
/tmp/ipykernel_8907/3606293857.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Geography'][df['Geography']=='Spain']=1
/tmp/ipykernel_8907/3606293857.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Geography'][df['Geography']=='Germany']=2
/tmp/ipykernel_8907/3606293857.py:4: SettingWithCopyWar

In [13]:
df.head()

CreditScore Geography Gender  Age  Tenure    Balance  NumOfProducts  \
0          619         0      1   42       2       0.00              1   
1          608         1      1   41       1   83807.86              1   
2          502         0      1   42       8  159660.80              3   
3          699         0      1   39       1       0.00              2   
4          850         1      1   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [14]:
X_train=df.drop(columns='Exited')
Y_train=df['Exited']

In [15]:
help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
    Split arrays or matrices into random train and test subsets.
    
    Quick utility that wraps input validation and
    ``next(ShuffleSplit().split(X, y))`` and application to input data
    into a single call for splitting (and optionally subsampling) data in a
    oneliner.
    
    Read more in the :ref:`User Guide <cross_validation>`.
    
    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.
    
    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to 

In [16]:
X_train1,X_test,Y_train1,Y_test=train_test_split(X_train,Y_train,test_size=0.2,shuffle=True,stratify=Y_train)

In [17]:
#X=StandardScaler().fit_transform(X_train1)


In [18]:
from sklearn.neural_network import MLPClassifier

In [19]:
cls=MLPClassifier(random_state=1,max_iter=300)

In [20]:
cls.fit(X_train1,Y_train1)

MLPClassifier(max_iter=300, random_state=1)

In [21]:
Y_pred=cls.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [23]:
a=accuracy_score(Y_test,Y_pred)

In [24]:
a

0.796

In [25]:
cm=confusion_matrix(Y_test,Y_pred)
cm

array([[1592,    1],
       [ 407,    0]])

In [26]:
x=[Y_test,Y_pred]

In [27]:
Y_test.head(100)

3871    0
6082    0
8222    0
5820    0
5513    0
       ..
705     1
1628    0
8452    1
5001    0
8383    0
Name: Exited, Length: 100, dtype: int64

In [28]:
Y_pred[:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
#pip install tabulate

Note: you may need to restart the kernel to use updated packages.


In [31]:
ef={'Actual':Y_test,'Predicted':Y_pred}
from tabulate import tabulate
print(tabulate(ef,headers='keys',tablefmt='psql'))

+----------+-------------+
|   Actual |   Predicted |
|----------+-------------|
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        1 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        1 |           0 |
|        1 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        0 |           0 |
|        1 |           0 |
|        0 |           0 |
|        0 |           0 |
|        1 |           0 |
|        0 |           0 |
|        0 |           0 |
|

In [34]:
ef['Actual'][:5]

/tmp/ipykernel_8907/3730136961.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  ef['Actual'][:5]


3871    0
6082    0
8222    0
5820    0
5513    0
Name: Exited, dtype: int64

In [35]:
ef['Predicted'][:5]

array([0, 0, 0, 0, 0])